# Copy this file to .github/workflows/agent-actions.yml in your repo.
# Set the ANTHROPIC_API_KEY secret in your repo settings.
name: Agent Actions

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  pull_request_review:
    types: [submitted]
  issues:
    types: [opened, labeled]

jobs:
  claude:
    uses: dwmkerr/agent-actions/.github/workflows/claude.yml@main
    secrets:
      anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
    # Uncomment to override defaults:
    # with:
    #   trigger_phrase: "@claude"
    #   timeout_minutes: 30
    #   allowed_users: "dwmkerr"
